version: '3.8'
services:
#  mysql:
#    platform: linux/x86_64
#    image: mysql:latest
#    container_name: kafka-test
#    restart: always
#    environment:
#      - 'MYSQL_DATABASE=kafka_test'
#      - 'MYSQL_PASSWORD=1234'
#      - 'MYSQL_ROOT_PASSWORD=1234'
#      - 'MYSQL_USER=root'
#    ports:
#      - "3306:3306"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME : 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181